server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/agenda?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 12345678
    initial-size: 10
    max-active: 20
    max-idle: 8
    min-idle: 8
    type: com.alibaba.druid.pool.DruidDataSource
  thymeleaf:
    mode: HTML5
    cache: false
    encoding: utf-8
#    suffix: .html
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.java.springboot.bean

logging:
  level:
    com:
      mq:
        agenda:
          user:
            mapper : debug
#    servlet: #文件上传限制
#      multipart:
#        max-file-size: 30MB
#        max-request-size: 100MB